// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAPIKeysForMerchant = `-- name: CountAPIKeysForMerchant :one
SELECT COUNT(*) FROM public.api_keys
WHERE merchant_id = $1 AND revoked_at IS NULL
`

func (q *Queries) CountAPIKeysForMerchant(ctx context.Context, merchantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAPIKeysForMerchant, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO public.api_keys (
    id, merchant_id, name, key_prefix, key_hash, scopes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, merchant_id, name, key_prefix, key_hash, scopes, last_used_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
	Name       string `json:"name"`
	KeyPrefix  string `json:"key_prefix"`
	KeyHash    string `json:"key_hash"`
	Scopes     string `json:"scopes"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, merchant_id, name, key_prefix, key_hash, scopes, last_used_at, created_at, revoked_at FROM public.api_keys
WHERE key_hash   = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, merchant_id, name, key_prefix, scopes, last_used_at, created_at, revoked_at
FROM public.api_keys
WHERE merchant_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         string       `json:"id"`
	MerchantID string       `json:"merchant_id"`
	Name       string       `json:"name"`
	KeyPrefix  string       `json:"key_prefix"`
	Scopes     string       `json:"scopes"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, merchantID string) ([]ListAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.KeyPrefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE public.api_keys
SET revoked_at = now()
WHERE id = $1 AND merchant_id = $2
`

type RevokeAPIKeyParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, arg.ID, arg.MerchantID)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE public.api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}
