// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO public.audit_logs (
    id, merchant_id, actor_user_id, actor_device_id, action, entity, entity_id, details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertAuditLogParams struct {
	ID            string          `json:"id"`
	MerchantID    sql.NullString  `json:"merchant_id"`
	ActorUserID   sql.NullString  `json:"actor_user_id"`
	ActorDeviceID sql.NullString  `json:"actor_device_id"`
	Action        string          `json:"action"`
	Entity        string          `json:"entity"`
	EntityID      string          `json:"entity_id"`
	Details       json.RawMessage `json:"details"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ID,
		arg.MerchantID,
		arg.ActorUserID,
		arg.ActorDeviceID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Details,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, merchant_id, actor_user_id, actor_device_id, action, entity, entity_id, details, created_at FROM public.audit_logs
WHERE ($1::text IS NULL OR merchant_id = $1)
  AND ($2::text IS NULL OR action      = $2)
  AND ($3::text IS NULL OR entity      = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type ListAuditLogsParams struct {
	Column1 string    `json:"column_1"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
	Column4 time.Time `json:"column_4"`
	Column5 time.Time `json:"column_5"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.ActorUserID,
			&i.ActorDeviceID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
