// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO public.devices (
    id, merchant_id, name, pairing_token, pairing_expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, merchant_id, name, model, android_version, app_version, secret_ciphertext, secret_nonce, status, failed_sig_count, last_heartbeat_at, last_sms_synced_at, pairing_token, pairing_expires_at, created_at
`

type CreateDeviceParams struct {
	ID               string         `json:"id"`
	MerchantID       string         `json:"merchant_id"`
	Name             string         `json:"name"`
	PairingToken     sql.NullString `json:"pairing_token"`
	PairingExpiresAt sql.NullTime   `json:"pairing_expires_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.PairingToken,
		arg.PairingExpiresAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Model,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.Status,
		&i.FailedSigCount,
		&i.LastHeartbeatAt,
		&i.LastSmsSyncedAt,
		&i.PairingToken,
		&i.PairingExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const disableDevice = `-- name: DisableDevice :exec
UPDATE public.devices SET status = 'disabled', failed_sig_count = 0 WHERE id = $1
`

func (q *Queries) DisableDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, disableDevice, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, merchant_id, name, model, android_version, app_version, secret_ciphertext, secret_nonce, status, failed_sig_count, last_heartbeat_at, last_sms_synced_at, pairing_token, pairing_expires_at, created_at FROM public.devices WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Model,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.Status,
		&i.FailedSigCount,
		&i.LastHeartbeatAt,
		&i.LastSmsSyncedAt,
		&i.PairingToken,
		&i.PairingExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByPairingToken = `-- name: GetDeviceByPairingToken :one
SELECT id, merchant_id, name, model, android_version, app_version, secret_ciphertext, secret_nonce, status, failed_sig_count, last_heartbeat_at, last_sms_synced_at, pairing_token, pairing_expires_at, created_at FROM public.devices
WHERE pairing_token = $1 AND pairing_expires_at > now()
LIMIT 1
`

func (q *Queries) GetDeviceByPairingToken(ctx context.Context, pairingToken sql.NullString) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByPairingToken, pairingToken)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Model,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.Status,
		&i.FailedSigCount,
		&i.LastHeartbeatAt,
		&i.LastSmsSyncedAt,
		&i.PairingToken,
		&i.PairingExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrFailedSigCount = `-- name: IncrFailedSigCount :one
UPDATE public.devices
SET failed_sig_count = failed_sig_count + 1
WHERE id = $1
RETURNING failed_sig_count
`

func (q *Queries) IncrFailedSigCount(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRowContext(ctx, incrFailedSigCount, id)
	var failed_sig_count int32
	err := row.Scan(&failed_sig_count)
	return failed_sig_count, err
}

const listAllDevicesForAdmin = `-- name: ListAllDevicesForAdmin :many
SELECT d.id, d.merchant_id, d.name, d.model, d.android_version, d.app_version, d.secret_ciphertext, d.secret_nonce, d.status, d.failed_sig_count, d.last_heartbeat_at, d.last_sms_synced_at, d.pairing_token, d.pairing_expires_at, d.created_at, m.name AS merchant_name
FROM public.devices d
JOIN public.merchants m ON m.id = d.merchant_id
ORDER BY d.last_heartbeat_at DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListAllDevicesForAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllDevicesForAdminRow struct {
	ID               string         `json:"id"`
	MerchantID       string         `json:"merchant_id"`
	Name             string         `json:"name"`
	Model            string         `json:"model"`
	AndroidVersion   string         `json:"android_version"`
	AppVersion       string         `json:"app_version"`
	SecretCiphertext []byte         `json:"secret_ciphertext"`
	SecretNonce      []byte         `json:"secret_nonce"`
	Status           string         `json:"status"`
	FailedSigCount   int32          `json:"failed_sig_count"`
	LastHeartbeatAt  sql.NullTime   `json:"last_heartbeat_at"`
	LastSmsSyncedAt  sql.NullTime   `json:"last_sms_synced_at"`
	PairingToken     sql.NullString `json:"pairing_token"`
	PairingExpiresAt sql.NullTime   `json:"pairing_expires_at"`
	CreatedAt        time.Time      `json:"created_at"`
	MerchantName     string         `json:"merchant_name"`
}

func (q *Queries) ListAllDevicesForAdmin(ctx context.Context, arg ListAllDevicesForAdminParams) ([]ListAllDevicesForAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDevicesForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDevicesForAdminRow{}
	for rows.Next() {
		var i ListAllDevicesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Model,
			&i.AndroidVersion,
			&i.AppVersion,
			&i.SecretCiphertext,
			&i.SecretNonce,
			&i.Status,
			&i.FailedSigCount,
			&i.LastHeartbeatAt,
			&i.LastSmsSyncedAt,
			&i.PairingToken,
			&i.PairingExpiresAt,
			&i.CreatedAt,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesForMerchant = `-- name: ListDevicesForMerchant :many
SELECT id, merchant_id, name, model, android_version, app_version, secret_ciphertext, secret_nonce, status, failed_sig_count, last_heartbeat_at, last_sms_synced_at, pairing_token, pairing_expires_at, created_at FROM public.devices WHERE merchant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDevicesForMerchant(ctx context.Context, merchantID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesForMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Model,
			&i.AndroidVersion,
			&i.AppVersion,
			&i.SecretCiphertext,
			&i.SecretNonce,
			&i.Status,
			&i.FailedSigCount,
			&i.LastHeartbeatAt,
			&i.LastSmsSyncedAt,
			&i.PairingToken,
			&i.PairingExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleDevices = `-- name: ListStaleDevices :many
SELECT id, merchant_id, name, model, android_version, app_version, secret_ciphertext, secret_nonce, status, failed_sig_count, last_heartbeat_at, last_sms_synced_at, pairing_token, pairing_expires_at, created_at FROM public.devices
WHERE status           = 'active'
  AND last_heartbeat_at < now() - interval '3 minutes'
`

func (q *Queries) ListStaleDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listStaleDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Model,
			&i.AndroidVersion,
			&i.AppVersion,
			&i.SecretCiphertext,
			&i.SecretNonce,
			&i.Status,
			&i.FailedSigCount,
			&i.LastHeartbeatAt,
			&i.LastSmsSyncedAt,
			&i.PairingToken,
			&i.PairingExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regeneratePairingToken = `-- name: RegeneratePairingToken :exec
UPDATE public.devices
SET pairing_token      = $2,
    pairing_expires_at = $3
WHERE id = $1
`

type RegeneratePairingTokenParams struct {
	ID               string         `json:"id"`
	PairingToken     sql.NullString `json:"pairing_token"`
	PairingExpiresAt sql.NullTime   `json:"pairing_expires_at"`
}

func (q *Queries) RegeneratePairingToken(ctx context.Context, arg RegeneratePairingTokenParams) error {
	_, err := q.db.ExecContext(ctx, regeneratePairingToken, arg.ID, arg.PairingToken, arg.PairingExpiresAt)
	return err
}

const resetFailedSigCount = `-- name: ResetFailedSigCount :exec
UPDATE public.devices SET failed_sig_count = 0 WHERE id = $1
`

func (q *Queries) ResetFailedSigCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, resetFailedSigCount, id)
	return err
}

const storePairedDevice = `-- name: StorePairedDevice :exec
UPDATE public.devices
SET secret_ciphertext = $2,
    secret_nonce      = $3,
    pairing_token     = NULL,
    pairing_expires_at = NULL,
    status            = 'active',
    failed_sig_count  = 0
WHERE id = $1
`

type StorePairedDeviceParams struct {
	ID               string `json:"id"`
	SecretCiphertext []byte `json:"secret_ciphertext"`
	SecretNonce      []byte `json:"secret_nonce"`
}

func (q *Queries) StorePairedDevice(ctx context.Context, arg StorePairedDeviceParams) error {
	_, err := q.db.ExecContext(ctx, storePairedDevice, arg.ID, arg.SecretCiphertext, arg.SecretNonce)
	return err
}

const updateDeviceMetadata = `-- name: UpdateDeviceMetadata :exec
UPDATE public.devices
SET name            = COALESCE(NULLIF($2, ''), name),
    model           = COALESCE(NULLIF($3, ''), model),
    android_version = COALESCE(NULLIF($4, ''), android_version),
    app_version     = COALESCE(NULLIF($5, ''), app_version)
WHERE id = $1
`

type UpdateDeviceMetadataParams struct {
	ID             string      `json:"id"`
	Name           interface{} `json:"name"`
	Model          interface{} `json:"model"`
	AndroidVersion interface{} `json:"android_version"`
	AppVersion     interface{} `json:"app_version"`
}

func (q *Queries) UpdateDeviceMetadata(ctx context.Context, arg UpdateDeviceMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceMetadata,
		arg.ID,
		arg.Name,
		arg.Model,
		arg.AndroidVersion,
		arg.AppVersion,
	)
	return err
}

const updateDeviceStatus = `-- name: UpdateDeviceStatus :exec
UPDATE public.devices SET status = $2 WHERE id = $1
`

type UpdateDeviceStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceStatus, arg.ID, arg.Status)
	return err
}

const updateHeartbeat = `-- name: UpdateHeartbeat :exec
UPDATE public.devices
SET last_heartbeat_at = now(),
    app_version       = $2
WHERE id = $1
`

type UpdateHeartbeatParams struct {
	ID         string `json:"id"`
	AppVersion string `json:"app_version"`
}

func (q *Queries) UpdateHeartbeat(ctx context.Context, arg UpdateHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, updateHeartbeat, arg.ID, arg.AppVersion)
	return err
}

const updateLastSMSSynced = `-- name: UpdateLastSMSSynced :exec
UPDATE public.devices SET last_sms_synced_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastSMSSynced(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLastSMSSynced, id)
	return err
}
