// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_announce.sql

package db

import (
	"context"
	"database/sql"
)

const addDomain = `-- name: AddDomain :one
INSERT INTO public.domain_whitelist (id, merchant_id, domain, added_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (merchant_id, domain) DO NOTHING
RETURNING id, merchant_id, domain, added_by, created_at
`

type AddDomainParams struct {
	ID         string         `json:"id"`
	MerchantID string         `json:"merchant_id"`
	Domain     string         `json:"domain"`
	AddedBy    sql.NullString `json:"added_by"`
}

func (q *Queries) AddDomain(ctx context.Context, arg AddDomainParams) (DomainWhitelist, error) {
	row := q.db.QueryRowContext(ctx, addDomain,
		arg.ID,
		arg.MerchantID,
		arg.Domain,
		arg.AddedBy,
	)
	var i DomainWhitelist
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Domain,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const checkDomainAllowed = `-- name: CheckDomainAllowed :one
SELECT id FROM public.domain_whitelist
WHERE merchant_id = $1 AND domain = $2
LIMIT 1
`

type CheckDomainAllowedParams struct {
	MerchantID string `json:"merchant_id"`
	Domain     string `json:"domain"`
}

func (q *Queries) CheckDomainAllowed(ctx context.Context, arg CheckDomainAllowedParams) (string, error) {
	row := q.db.QueryRowContext(ctx, checkDomainAllowed, arg.MerchantID, arg.Domain)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO public.announcements (id, title, body, severity, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, body, severity, expires_at, created_at
`

type CreateAnnouncementParams struct {
	ID        string       `json:"id"`
	Title     string       `json:"title"`
	Body      string       `json:"body"`
	Severity  string       `json:"severity"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRowContext(ctx, createAnnouncement,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Severity,
		arg.ExpiresAt,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Severity,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAnnouncementsAdmin = `-- name: ListAnnouncementsAdmin :many
SELECT id, title, body, severity, expires_at, created_at FROM public.announcements
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAnnouncementsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAnnouncementsAdmin(ctx context.Context, arg ListAnnouncementsAdminParams) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncementsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(&i.ID, &i.Title, &i.Body, &i.Severity, &i.ExpiresAt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE public.announcements
SET title = $2,
    body = $3,
    severity = $4,
    expires_at = $5
WHERE id = $1
RETURNING id, title, body, severity, expires_at, created_at
`

type UpdateAnnouncementParams struct {
	ID        string       `json:"id"`
	Title     string       `json:"title"`
	Body      string       `json:"body"`
	Severity  string       `json:"severity"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRowContext(ctx, updateAnnouncement, arg.ID, arg.Title, arg.Body, arg.Severity, arg.ExpiresAt)
	var i Announcement
	err := row.Scan(&i.ID, &i.Title, &i.Body, &i.Severity, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM public.announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAnnouncement, id)
	return err
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
SELECT id, title, body, severity, expires_at, created_at FROM public.announcements
WHERE expires_at IS NULL OR expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Severity,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, merchant_id, domain, added_by, created_at FROM public.domain_whitelist WHERE merchant_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListDomains(ctx context.Context, merchantID string) ([]DomainWhitelist, error) {
	rows, err := q.db.QueryContext(ctx, listDomains, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainWhitelist{}
	for rows.Next() {
		var i DomainWhitelist
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Domain,
			&i.AddedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDomain = `-- name: RemoveDomain :exec
DELETE FROM public.domain_whitelist WHERE id = $1 AND merchant_id = $2
`

type RemoveDomainParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) RemoveDomain(ctx context.Context, arg RemoveDomainParams) error {
	_, err := q.db.ExecContext(ctx, removeDomain, arg.ID, arg.MerchantID)
	return err
}
