// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM public.idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, merchant_id, request_hash, response_body, status_code, created_at, expires_at FROM public.idempotency_keys
WHERE key         = $1
  AND merchant_id = $2
  AND expires_at  > now()
LIMIT 1
`

type GetIdempotencyKeyParams struct {
	Key        string `json:"key"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.Key, arg.MerchantID)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.MerchantID,
		&i.RequestHash,
		&i.ResponseBody,
		&i.StatusCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertIdempotencyKey = `-- name: UpsertIdempotencyKey :exec
INSERT INTO public.idempotency_keys (key, merchant_id, request_hash, response_body, status_code)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO NOTHING
`

type UpsertIdempotencyKeyParams struct {
	Key          string `json:"key"`
	MerchantID   string `json:"merchant_id"`
	RequestHash  string `json:"request_hash"`
	ResponseBody []byte `json:"response_body"`
	StatusCode   int32  `json:"status_code"`
}

func (q *Queries) UpsertIdempotencyKey(ctx context.Context, arg UpsertIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertIdempotencyKey,
		arg.Key,
		arg.MerchantID,
		arg.RequestHash,
		arg.ResponseBody,
		arg.StatusCode,
	)
	return err
}
