// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const disableMerchant = `-- name: DisableMerchant :exec
UPDATE public.merchants
SET plan_status = 'disabled'
WHERE id = $1
`

func (q *Queries) DisableMerchant(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, disableMerchant, id)
	return err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, owner_user_id, name, slug, logo_url, favicon_url, brand_color, support_email, support_phone, plan_id, plan_status, plan_renews_at, session_count_current_period, settings, created_at FROM public.merchants WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMerchant(ctx context.Context, id string) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BrandColor,
		&i.SupportEmail,
		&i.SupportPhone,
		&i.PlanID,
		&i.PlanStatus,
		&i.PlanRenewsAt,
		&i.SessionCountCurrentPeriod,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantAdmin = `-- name: GetMerchantAdmin :one
SELECT m.id, m.owner_user_id, m.name, m.slug, m.logo_url, m.favicon_url, m.brand_color, m.support_email, m.support_phone, m.plan_id, m.plan_status, m.plan_renews_at, m.session_count_current_period, m.settings, m.created_at,
       (SELECT COUNT(*) FROM public.devices        WHERE merchant_id = m.id) AS device_count,
       (SELECT COUNT(*) FROM public.checkout_sessions WHERE merchant_id = m.id) AS total_sessions
FROM public.merchants m
WHERE m.id = $1
`

type GetMerchantAdminRow struct {
	ID                        string          `json:"id"`
	OwnerUserID               string          `json:"owner_user_id"`
	Name                      string          `json:"name"`
	Slug                      string          `json:"slug"`
	LogoUrl                   string          `json:"logo_url"`
	FaviconUrl                string          `json:"favicon_url"`
	BrandColor                string          `json:"brand_color"`
	SupportEmail              string          `json:"support_email"`
	SupportPhone              string          `json:"support_phone"`
	PlanID                    string          `json:"plan_id"`
	PlanStatus                string          `json:"plan_status"`
	PlanRenewsAt              sql.NullTime    `json:"plan_renews_at"`
	SessionCountCurrentPeriod int64           `json:"session_count_current_period"`
	Settings                  json.RawMessage `json:"settings"`
	CreatedAt                 time.Time       `json:"created_at"`
	DeviceCount               int64           `json:"device_count"`
	TotalSessions             int64           `json:"total_sessions"`
}

func (q *Queries) GetMerchantAdmin(ctx context.Context, id string) (GetMerchantAdminRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchantAdmin, id)
	var i GetMerchantAdminRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BrandColor,
		&i.SupportEmail,
		&i.SupportPhone,
		&i.PlanID,
		&i.PlanStatus,
		&i.PlanRenewsAt,
		&i.SessionCountCurrentPeriod,
		&i.Settings,
		&i.CreatedAt,
		&i.DeviceCount,
		&i.TotalSessions,
	)
	return i, err
}

const getMerchantByOwner = `-- name: GetMerchantByOwner :one
SELECT id, owner_user_id, name, slug, logo_url, favicon_url, brand_color, support_email, support_phone, plan_id, plan_status, plan_renews_at, session_count_current_period, settings, created_at FROM public.merchants WHERE owner_user_id = $1 LIMIT 1
`

func (q *Queries) GetMerchantByOwner(ctx context.Context, ownerUserID string) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByOwner, ownerUserID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.BrandColor,
		&i.SupportEmail,
		&i.SupportPhone,
		&i.PlanID,
		&i.PlanStatus,
		&i.PlanRenewsAt,
		&i.SessionCountCurrentPeriod,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT code, price_bdt_monthly, limits FROM public.plans WHERE code = $1 LIMIT 1
`

func (q *Queries) GetPlan(ctx context.Context, code string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, code)
	var i Plan
	err := row.Scan(&i.Code, &i.PriceBdtMonthly, &i.Limits)
	return i, err
}

const listMerchantsAdmin = `-- name: ListMerchantsAdmin :many
SELECT m.id, m.owner_user_id, m.name, m.slug, m.logo_url, m.favicon_url, m.brand_color, m.support_email, m.support_phone, m.plan_id, m.plan_status, m.plan_renews_at, m.session_count_current_period, m.settings, m.created_at,
       (SELECT COUNT(*) FROM public.devices        WHERE merchant_id = m.id) AS device_count,
       (SELECT COUNT(*) FROM public.checkout_sessions WHERE merchant_id = m.id AND status = 'succeeded') AS total_payments
FROM public.merchants m
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type ListMerchantsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMerchantsAdminRow struct {
	ID                        string          `json:"id"`
	OwnerUserID               string          `json:"owner_user_id"`
	Name                      string          `json:"name"`
	Slug                      string          `json:"slug"`
	LogoUrl                   string          `json:"logo_url"`
	FaviconUrl                string          `json:"favicon_url"`
	BrandColor                string          `json:"brand_color"`
	SupportEmail              string          `json:"support_email"`
	SupportPhone              string          `json:"support_phone"`
	PlanID                    string          `json:"plan_id"`
	PlanStatus                string          `json:"plan_status"`
	PlanRenewsAt              sql.NullTime    `json:"plan_renews_at"`
	SessionCountCurrentPeriod int64           `json:"session_count_current_period"`
	Settings                  json.RawMessage `json:"settings"`
	CreatedAt                 time.Time       `json:"created_at"`
	DeviceCount               int64           `json:"device_count"`
	TotalPayments             int64           `json:"total_payments"`
}

func (q *Queries) ListMerchantsAdmin(ctx context.Context, arg ListMerchantsAdminParams) ([]ListMerchantsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listMerchantsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantsAdminRow{}
	for rows.Next() {
		var i ListMerchantsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.FaviconUrl,
			&i.BrandColor,
			&i.SupportEmail,
			&i.SupportPhone,
			&i.PlanID,
			&i.PlanStatus,
			&i.PlanRenewsAt,
			&i.SessionCountCurrentPeriod,
			&i.Settings,
			&i.CreatedAt,
			&i.DeviceCount,
			&i.TotalPayments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchantBranding = `-- name: UpdateMerchantBranding :exec
UPDATE public.merchants
SET name          = $2,
    logo_url      = $3,
    favicon_url   = $4,
    brand_color   = $5,
    support_email = $6,
    support_phone = $7
WHERE id = $1
`

type UpdateMerchantBrandingParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	LogoUrl      string `json:"logo_url"`
	FaviconUrl   string `json:"favicon_url"`
	BrandColor   string `json:"brand_color"`
	SupportEmail string `json:"support_email"`
	SupportPhone string `json:"support_phone"`
}

func (q *Queries) UpdateMerchantBranding(ctx context.Context, arg UpdateMerchantBrandingParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchantBranding,
		arg.ID,
		arg.Name,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.BrandColor,
		arg.SupportEmail,
		arg.SupportPhone,
	)
	return err
}

const updateMerchantPlan = `-- name: UpdateMerchantPlan :exec
UPDATE public.merchants
SET plan_id        = $2,
    plan_status    = $3,
    plan_renews_at = $4
WHERE id = $1
`

type UpdateMerchantPlanParams struct {
	ID           string       `json:"id"`
	PlanID       string       `json:"plan_id"`
	PlanStatus   string       `json:"plan_status"`
	PlanRenewsAt sql.NullTime `json:"plan_renews_at"`
}

func (q *Queries) UpdateMerchantPlan(ctx context.Context, arg UpdateMerchantPlanParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchantPlan,
		arg.ID,
		arg.PlanID,
		arg.PlanStatus,
		arg.PlanRenewsAt,
	)
	return err
}

const updateMerchantSettings = `-- name: UpdateMerchantSettings :exec
UPDATE public.merchants
SET settings = $2
WHERE id = $1
`

type UpdateMerchantSettingsParams struct {
	ID       string          `json:"id"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) UpdateMerchantSettings(ctx context.Context, arg UpdateMerchantSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchantSettings, arg.ID, arg.Settings)
	return err
}
