// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Announcement struct {
	ID        string       `json:"id"`
	Title     string       `json:"title"`
	Body      string       `json:"body"`
	Severity  string       `json:"severity"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type ApiKey struct {
	ID         string       `json:"id"`
	MerchantID string       `json:"merchant_id"`
	Name       string       `json:"name"`
	KeyPrefix  string       `json:"key_prefix"`
	KeyHash    string       `json:"key_hash"`
	Scopes     string       `json:"scopes"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type AuditLog struct {
	ID            string          `json:"id"`
	MerchantID    sql.NullString  `json:"merchant_id"`
	ActorUserID   sql.NullString  `json:"actor_user_id"`
	ActorDeviceID sql.NullString  `json:"actor_device_id"`
	Action        string          `json:"action"`
	Entity        string          `json:"entity"`
	EntityID      string          `json:"entity_id"`
	Details       json.RawMessage `json:"details"`
	CreatedAt     time.Time       `json:"created_at"`
}

type CheckoutSession struct {
	ID                string          `json:"id"`
	MerchantID        string          `json:"merchant_id"`
	PaymentProfileID  string          `json:"payment_profile_id"`
	Source            string          `json:"source"`
	Amount            int64           `json:"amount"`
	Currency          string          `json:"currency"`
	Customer          json.RawMessage `json:"customer"`
	Metadata          json.RawMessage `json:"metadata"`
	SenderNumberClaim sql.NullString  `json:"sender_number_claim"`
	TrxIDClaim        sql.NullString  `json:"trx_id_claim"`
	ClaimSubmittedAt  sql.NullTime    `json:"claim_submitted_at"`
	ConfirmedAt       sql.NullTime    `json:"confirmed_at"`
	Status            string          `json:"status"`
	NeedsReview       bool            `json:"needs_review"`
	ReviewReason      sql.NullString  `json:"review_reason"`
	ExpiresAt         time.Time       `json:"expires_at"`
	ReturnUrl         string          `json:"return_url"`
	CancelUrl         string          `json:"cancel_url"`
	PaymentLinkID     sql.NullString  `json:"payment_link_id"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type Device struct {
	ID               string         `json:"id"`
	MerchantID       string         `json:"merchant_id"`
	Name             string         `json:"name"`
	Model            string         `json:"model"`
	AndroidVersion   string         `json:"android_version"`
	AppVersion       string         `json:"app_version"`
	SecretCiphertext []byte         `json:"secret_ciphertext"`
	SecretNonce      []byte         `json:"secret_nonce"`
	Status           string         `json:"status"`
	FailedSigCount   int32          `json:"failed_sig_count"`
	LastHeartbeatAt  sql.NullTime   `json:"last_heartbeat_at"`
	LastSmsSyncedAt  sql.NullTime   `json:"last_sms_synced_at"`
	PairingToken     sql.NullString `json:"pairing_token"`
	PairingExpiresAt sql.NullTime   `json:"pairing_expires_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type DomainWhitelist struct {
	ID         string         `json:"id"`
	MerchantID string         `json:"merchant_id"`
	Domain     string         `json:"domain"`
	AddedBy    sql.NullString `json:"added_by"`
	CreatedAt  time.Time      `json:"created_at"`
}

type IdempotencyKey struct {
	Key          string    `json:"key"`
	MerchantID   string    `json:"merchant_id"`
	RequestHash  string    `json:"request_hash"`
	ResponseBody []byte    `json:"response_body"`
	StatusCode   int32     `json:"status_code"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type Merchant struct {
	ID                        string          `json:"id"`
	OwnerUserID               string          `json:"owner_user_id"`
	Name                      string          `json:"name"`
	Slug                      string          `json:"slug"`
	LogoUrl                   string          `json:"logo_url"`
	FaviconUrl                string          `json:"favicon_url"`
	BrandColor                string          `json:"brand_color"`
	SupportEmail              string          `json:"support_email"`
	SupportPhone              string          `json:"support_phone"`
	PlanID                    string          `json:"plan_id"`
	PlanStatus                string          `json:"plan_status"`
	PlanRenewsAt              sql.NullTime    `json:"plan_renews_at"`
	SessionCountCurrentPeriod int64           `json:"session_count_current_period"`
	Settings                  json.RawMessage `json:"settings"`
	CreatedAt                 time.Time       `json:"created_at"`
}

type MfsOtpVerification struct {
	ID          string    `json:"id"`
	MerchantID  string    `json:"merchant_id"`
	MfsNumber   string    `json:"mfs_number"`
	Provider    string    `json:"provider"`
	AccountType string    `json:"account_type"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type Payment struct {
	ID                 string         `json:"id"`
	MerchantID         string         `json:"merchant_id"`
	SessionID          string         `json:"session_id"`
	SmsID              sql.NullString `json:"sms_id"`
	Provider           string         `json:"provider"`
	AccountType        string         `json:"account_type"`
	SenderNumber       string         `json:"sender_number"`
	TrxID              string         `json:"trx_id"`
	Amount             int64          `json:"amount"`
	BalanceAfter       sql.NullInt64  `json:"balance_after"`
	VerifiedAt         time.Time      `json:"verified_at"`
	VerificationSource string         `json:"verification_source"`
	IsRefundFlagged    bool           `json:"is_refund_flagged"`
	RefundNote         sql.NullString `json:"refund_note"`
	CreatedAt          time.Time      `json:"created_at"`
}

type PaymentLink struct {
	ID               string        `json:"id"`
	MerchantID       string        `json:"merchant_id"`
	PaymentProfileID string        `json:"payment_profile_id"`
	Title            string        `json:"title"`
	Amount           sql.NullInt64 `json:"amount"`
	Reusable         bool          `json:"reusable"`
	Active           bool          `json:"active"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
	CreatedAt        time.Time     `json:"created_at"`
}

type PaymentProfile struct {
	ID                  string         `json:"id"`
	MerchantID          string         `json:"merchant_id"`
	Provider            string         `json:"provider"`
	AccountType         string         `json:"account_type"`
	MfsNumber           string         `json:"mfs_number"`
	DisplayName         string         `json:"display_name"`
	DeviceID            sql.NullString `json:"device_id"`
	SimSlot             sql.NullInt32  `json:"sim_slot"`
	TrackedBalance      sql.NullInt64  `json:"tracked_balance"`
	BalanceVerification bool           `json:"balance_verification"`
	BalanceLastSyncedAt sql.NullTime   `json:"balance_last_synced_at"`
	Status              string         `json:"status"`
	IsOtpVerified       bool           `json:"is_otp_verified"`
	CreatedAt           time.Time      `json:"created_at"`
}

type Plan struct {
	Code            string          `json:"code"`
	PriceBdtMonthly int64           `json:"price_bdt_monthly"`
	Limits          json.RawMessage `json:"limits"`
}

type SmsMessage struct {
	ID               string                `json:"id"`
	MerchantID       string                `json:"merchant_id"`
	DeviceID         sql.NullString        `json:"device_id"`
	PaymentProfileID sql.NullString        `json:"payment_profile_id"`
	Provider         string                `json:"provider"`
	AccountType      string                `json:"account_type"`
	RawText          string                `json:"raw_text"`
	Parsed           pqtype.NullRawMessage `json:"parsed"`
	ParseStatus      string                `json:"parse_status"`
	MatchStatus      string                `json:"match_status"`
	MatchedSessionID sql.NullString        `json:"matched_session_id"`
	Source           string                `json:"source"`
	SimSlot          sql.NullInt32         `json:"sim_slot"`
	ReceivedAt       time.Time             `json:"received_at"`
	CreatedAt        time.Time             `json:"created_at"`
}

type TeamMember struct {
	MerchantID string         `json:"merchant_id"`
	UserID     string         `json:"user_id"`
	Role       string         `json:"role"`
	InvitedBy  sql.NullString `json:"invited_by"`
	CreatedAt  time.Time      `json:"created_at"`
}

type User struct {
	ID              string    `json:"id"`
	Email           string    `json:"email"`
	FullName        string    `json:"full_name"`
	AvatarUrl       string    `json:"avatar_url"`
	IsPlatformAdmin bool      `json:"is_platform_admin"`
	Locale          string    `json:"locale"`
	CreatedAt       time.Time `json:"created_at"`
}

type WebhookDelivery struct {
	ID               string          `json:"id"`
	EndpointID       string          `json:"endpoint_id"`
	MerchantID       string          `json:"merchant_id"`
	EventType        string          `json:"event_type"`
	Payload          json.RawMessage `json:"payload"`
	AttemptCount     int32           `json:"attempt_count"`
	NextRetryAt      time.Time       `json:"next_retry_at"`
	Status           string          `json:"status"`
	LastResponseCode sql.NullInt32   `json:"last_response_code"`
	CreatedAt        time.Time       `json:"created_at"`
	DeliveredAt      sql.NullTime    `json:"delivered_at"`
}

type WebhookEndpoint struct {
	ID         string          `json:"id"`
	MerchantID string          `json:"merchant_id"`
	Url        string          `json:"url"`
	Secret     string          `json:"secret"`
	Events     json.RawMessage `json:"events"`
	Status     string          `json:"status"`
	CreatedAt  time.Time       `json:"created_at"`
}
