// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package db

import (
	"context"
)

const createOTPVerification = `-- name: CreateOTPVerification :one
INSERT INTO public.mfs_otp_verifications (
    id, merchant_id, mfs_number, provider, account_type
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, merchant_id, mfs_number, provider, account_type, status, created_at, expires_at
`

type CreateOTPVerificationParams struct {
	ID          string `json:"id"`
	MerchantID  string `json:"merchant_id"`
	MfsNumber   string `json:"mfs_number"`
	Provider    string `json:"provider"`
	AccountType string `json:"account_type"`
}

func (q *Queries) CreateOTPVerification(ctx context.Context, arg CreateOTPVerificationParams) (MfsOtpVerification, error) {
	row := q.db.QueryRowContext(ctx, createOTPVerification,
		arg.ID,
		arg.MerchantID,
		arg.MfsNumber,
		arg.Provider,
		arg.AccountType,
	)
	var i MfsOtpVerification
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.MfsNumber,
		&i.Provider,
		&i.AccountType,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const expireOldOTPs = `-- name: ExpireOldOTPs :exec
UPDATE public.mfs_otp_verifications
SET status = 'expired'
WHERE status = 'pending' AND expires_at < now()
`

func (q *Queries) ExpireOldOTPs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireOldOTPs)
	return err
}

const getOTPVerification = `-- name: GetOTPVerification :one
SELECT id, merchant_id, mfs_number, provider, account_type, status, created_at, expires_at FROM public.mfs_otp_verifications
WHERE id = $1 AND merchant_id = $2
LIMIT 1
`

type GetOTPVerificationParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetOTPVerification(ctx context.Context, arg GetOTPVerificationParams) (MfsOtpVerification, error) {
	row := q.db.QueryRowContext(ctx, getOTPVerification, arg.ID, arg.MerchantID)
	var i MfsOtpVerification
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.MfsNumber,
		&i.Provider,
		&i.AccountType,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPendingOTPByNumber = `-- name: GetPendingOTPByNumber :one
SELECT id, merchant_id, mfs_number, provider, account_type, status, created_at, expires_at FROM public.mfs_otp_verifications
WHERE mfs_number = $1
  AND provider   = $2
  AND status     = 'pending'
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetPendingOTPByNumberParams struct {
	MfsNumber string `json:"mfs_number"`
	Provider  string `json:"provider"`
}

func (q *Queries) GetPendingOTPByNumber(ctx context.Context, arg GetPendingOTPByNumberParams) (MfsOtpVerification, error) {
	row := q.db.QueryRowContext(ctx, getPendingOTPByNumber, arg.MfsNumber, arg.Provider)
	var i MfsOtpVerification
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.MfsNumber,
		&i.Provider,
		&i.AccountType,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE public.mfs_otp_verifications
SET status = 'verified'
WHERE id = $1
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markOTPVerified, id)
	return err
}
