// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_links.sql

package db

import (
	"context"
	"database/sql"
)

const createPaymentLink = `-- name: CreatePaymentLink :one
INSERT INTO public.payment_links (
    id, merchant_id, payment_profile_id, title, amount, reusable, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, merchant_id, payment_profile_id, title, amount, reusable, active, expires_at, created_at
`

type CreatePaymentLinkParams struct {
	ID               string        `json:"id"`
	MerchantID       string        `json:"merchant_id"`
	PaymentProfileID string        `json:"payment_profile_id"`
	Title            string        `json:"title"`
	Amount           sql.NullInt64 `json:"amount"`
	Reusable         bool          `json:"reusable"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreatePaymentLink(ctx context.Context, arg CreatePaymentLinkParams) (PaymentLink, error) {
	row := q.db.QueryRowContext(ctx, createPaymentLink,
		arg.ID,
		arg.MerchantID,
		arg.PaymentProfileID,
		arg.Title,
		arg.Amount,
		arg.Reusable,
		arg.ExpiresAt,
	)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentProfileID,
		&i.Title,
		&i.Amount,
		&i.Reusable,
		&i.Active,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentLink = `-- name: GetPaymentLink :one
SELECT id, merchant_id, payment_profile_id, title, amount, reusable, active, expires_at, created_at FROM public.payment_links
WHERE id = $1 AND merchant_id = $2
LIMIT 1
`

type GetPaymentLinkParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetPaymentLink(ctx context.Context, arg GetPaymentLinkParams) (PaymentLink, error) {
	row := q.db.QueryRowContext(ctx, getPaymentLink, arg.ID, arg.MerchantID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentProfileID,
		&i.Title,
		&i.Amount,
		&i.Reusable,
		&i.Active,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentLinks = `-- name: ListPaymentLinks :many
SELECT id, merchant_id, payment_profile_id, title, amount, reusable, active, expires_at, created_at FROM public.payment_links
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentLinks(ctx context.Context, merchantID string) ([]PaymentLink, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentLinks, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentLink{}
	for rows.Next() {
		var i PaymentLink
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.PaymentProfileID,
			&i.Title,
			&i.Amount,
			&i.Reusable,
			&i.Active,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentLinkStatus = `-- name: UpdatePaymentLinkStatus :exec
UPDATE public.payment_links SET active = $3 WHERE id = $1 AND merchant_id = $2
`

type UpdatePaymentLinkStatusParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
	Active     bool   `json:"active"`
}

func (q *Queries) UpdatePaymentLinkStatus(ctx context.Context, arg UpdatePaymentLinkStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentLinkStatus, arg.ID, arg.MerchantID, arg.Active)
	return err
}
