// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*) FROM public.payments
WHERE merchant_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
  AND ($4::text        IS NULL OR provider   = $4)
`

type CountPaymentsParams struct {
	MerchantID string    `json:"merchant_id"`
	Column2    time.Time `json:"column_2"`
	Column3    time.Time `json:"column_3"`
	Column4    string    `json:"column_4"`
}

func (q *Queries) CountPayments(ctx context.Context, arg CountPaymentsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPayments,
		arg.MerchantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, merchant_id, session_id, sms_id, provider, account_type, sender_number, trx_id, amount, balance_after, verified_at, verification_source, is_refund_flagged, refund_note, created_at FROM public.payments
WHERE id = $1 AND merchant_id = $2
LIMIT 1
`

type GetPaymentParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, arg.ID, arg.MerchantID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SessionID,
		&i.SmsID,
		&i.Provider,
		&i.AccountType,
		&i.SenderNumber,
		&i.TrxID,
		&i.Amount,
		&i.BalanceAfter,
		&i.VerifiedAt,
		&i.VerificationSource,
		&i.IsRefundFlagged,
		&i.RefundNote,
		&i.CreatedAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO public.payments (
    id, merchant_id, session_id, sms_id, provider, account_type,
    sender_number, trx_id, amount, balance_after, verified_at, verification_source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (session_id, trx_id) DO NOTHING
RETURNING id, merchant_id, session_id, sms_id, provider, account_type, sender_number, trx_id, amount, balance_after, verified_at, verification_source, is_refund_flagged, refund_note, created_at
`

type InsertPaymentParams struct {
	ID                 string         `json:"id"`
	MerchantID         string         `json:"merchant_id"`
	SessionID          string         `json:"session_id"`
	SmsID              sql.NullString `json:"sms_id"`
	Provider           string         `json:"provider"`
	AccountType        string         `json:"account_type"`
	SenderNumber       string         `json:"sender_number"`
	TrxID              string         `json:"trx_id"`
	Amount             int64          `json:"amount"`
	BalanceAfter       sql.NullInt64  `json:"balance_after"`
	VerifiedAt         time.Time      `json:"verified_at"`
	VerificationSource string         `json:"verification_source"`
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, insertPayment,
		arg.ID,
		arg.MerchantID,
		arg.SessionID,
		arg.SmsID,
		arg.Provider,
		arg.AccountType,
		arg.SenderNumber,
		arg.TrxID,
		arg.Amount,
		arg.BalanceAfter,
		arg.VerifiedAt,
		arg.VerificationSource,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.SessionID,
		&i.SmsID,
		&i.Provider,
		&i.AccountType,
		&i.SenderNumber,
		&i.TrxID,
		&i.Amount,
		&i.BalanceAfter,
		&i.VerifiedAt,
		&i.VerificationSource,
		&i.IsRefundFlagged,
		&i.RefundNote,
		&i.CreatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, merchant_id, session_id, sms_id, provider, account_type, sender_number, trx_id, amount, balance_after, verified_at, verification_source, is_refund_flagged, refund_note, created_at FROM public.payments
WHERE merchant_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
  AND ($4::text        IS NULL OR provider   = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListPaymentsParams struct {
	MerchantID string    `json:"merchant_id"`
	Column2    time.Time `json:"column_2"`
	Column3    time.Time `json:"column_3"`
	Column4    string    `json:"column_4"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments,
		arg.MerchantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.SessionID,
			&i.SmsID,
			&i.Provider,
			&i.AccountType,
			&i.SenderNumber,
			&i.TrxID,
			&i.Amount,
			&i.BalanceAfter,
			&i.VerifiedAt,
			&i.VerificationSource,
			&i.IsRefundFlagged,
			&i.RefundNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
