// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_profiles.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const bindDevice = `-- name: BindDevice :exec
UPDATE public.payment_profiles
SET device_id = $3,
    sim_slot  = $4
WHERE id = $1 AND merchant_id = $2
`

type BindDeviceParams struct {
	ID         string         `json:"id"`
	MerchantID string         `json:"merchant_id"`
	DeviceID   sql.NullString `json:"device_id"`
	SimSlot    sql.NullInt32  `json:"sim_slot"`
}

func (q *Queries) BindDevice(ctx context.Context, arg BindDeviceParams) error {
	_, err := q.db.ExecContext(ctx, bindDevice,
		arg.ID,
		arg.MerchantID,
		arg.DeviceID,
		arg.SimSlot,
	)
	return err
}

const countProfilesForMerchant = `-- name: CountProfilesForMerchant :one
SELECT COUNT(*) FROM public.payment_profiles WHERE merchant_id = $1
`

func (q *Queries) CountProfilesForMerchant(ctx context.Context, merchantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProfilesForMerchant, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO public.payment_profiles (
    id, merchant_id, provider, account_type, mfs_number, display_name,
    balance_verification, is_otp_verified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, merchant_id, provider, account_type, mfs_number, display_name, device_id, sim_slot, tracked_balance, balance_verification, balance_last_synced_at, status, is_otp_verified, created_at
`

type CreateProfileParams struct {
	ID                  string `json:"id"`
	MerchantID          string `json:"merchant_id"`
	Provider            string `json:"provider"`
	AccountType         string `json:"account_type"`
	MfsNumber           string `json:"mfs_number"`
	DisplayName         string `json:"display_name"`
	BalanceVerification bool   `json:"balance_verification"`
	IsOtpVerified       bool   `json:"is_otp_verified"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (PaymentProfile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.MerchantID,
		arg.Provider,
		arg.AccountType,
		arg.MfsNumber,
		arg.DisplayName,
		arg.BalanceVerification,
		arg.IsOtpVerified,
	)
	var i PaymentProfile
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Provider,
		&i.AccountType,
		&i.MfsNumber,
		&i.DisplayName,
		&i.DeviceID,
		&i.SimSlot,
		&i.TrackedBalance,
		&i.BalanceVerification,
		&i.BalanceLastSyncedAt,
		&i.Status,
		&i.IsOtpVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, merchant_id, provider, account_type, mfs_number, display_name, device_id, sim_slot, tracked_balance, balance_verification, balance_last_synced_at, status, is_otp_verified, created_at FROM public.payment_profiles
WHERE id = $1 AND merchant_id = $2
LIMIT 1
`

type GetProfileParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetProfile(ctx context.Context, arg GetProfileParams) (PaymentProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, arg.ID, arg.MerchantID)
	var i PaymentProfile
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Provider,
		&i.AccountType,
		&i.MfsNumber,
		&i.DisplayName,
		&i.DeviceID,
		&i.SimSlot,
		&i.TrackedBalance,
		&i.BalanceVerification,
		&i.BalanceLastSyncedAt,
		&i.Status,
		&i.IsOtpVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByMerchantAndID = `-- name: GetProfileByMerchantAndID :one
SELECT id, merchant_id, provider, account_type, mfs_number, display_name, device_id, sim_slot, tracked_balance, balance_verification, balance_last_synced_at, status, is_otp_verified, created_at FROM public.payment_profiles
WHERE id = $1 AND merchant_id = $2
LIMIT 1
`

type GetProfileByMerchantAndIDParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetProfileByMerchantAndID(ctx context.Context, arg GetProfileByMerchantAndIDParams) (PaymentProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByMerchantAndID, arg.ID, arg.MerchantID)
	var i PaymentProfile
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Provider,
		&i.AccountType,
		&i.MfsNumber,
		&i.DisplayName,
		&i.DeviceID,
		&i.SimSlot,
		&i.TrackedBalance,
		&i.BalanceVerification,
		&i.BalanceLastSyncedAt,
		&i.Status,
		&i.IsOtpVerified,
		&i.CreatedAt,
	)
	return i, err
}

const listProfilesForMerchant = `-- name: ListProfilesForMerchant :many
SELECT pp.id, pp.merchant_id, pp.provider, pp.account_type, pp.mfs_number, pp.display_name, pp.device_id, pp.sim_slot, pp.tracked_balance, pp.balance_verification, pp.balance_last_synced_at, pp.status, pp.is_otp_verified, pp.created_at,
       d.name  AS device_name,
       d.status AS device_status
FROM public.payment_profiles pp
LEFT JOIN public.devices d ON d.id = pp.device_id
WHERE pp.merchant_id = $1
ORDER BY pp.created_at ASC
`

type ListProfilesForMerchantRow struct {
	ID                  string         `json:"id"`
	MerchantID          string         `json:"merchant_id"`
	Provider            string         `json:"provider"`
	AccountType         string         `json:"account_type"`
	MfsNumber           string         `json:"mfs_number"`
	DisplayName         string         `json:"display_name"`
	DeviceID            sql.NullString `json:"device_id"`
	SimSlot             sql.NullInt32  `json:"sim_slot"`
	TrackedBalance      sql.NullInt64  `json:"tracked_balance"`
	BalanceVerification bool           `json:"balance_verification"`
	BalanceLastSyncedAt sql.NullTime   `json:"balance_last_synced_at"`
	Status              string         `json:"status"`
	IsOtpVerified       bool           `json:"is_otp_verified"`
	CreatedAt           time.Time      `json:"created_at"`
	DeviceName          sql.NullString `json:"device_name"`
	DeviceStatus        sql.NullString `json:"device_status"`
}

func (q *Queries) ListProfilesForMerchant(ctx context.Context, merchantID string) ([]ListProfilesForMerchantRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfilesForMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilesForMerchantRow{}
	for rows.Next() {
		var i ListProfilesForMerchantRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Provider,
			&i.AccountType,
			&i.MfsNumber,
			&i.DisplayName,
			&i.DeviceID,
			&i.SimSlot,
			&i.TrackedBalance,
			&i.BalanceVerification,
			&i.BalanceLastSyncedAt,
			&i.Status,
			&i.IsOtpVerified,
			&i.CreatedAt,
			&i.DeviceName,
			&i.DeviceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE public.payment_profiles
SET display_name = $3,
    sim_slot     = $4
WHERE id = $1 AND merchant_id = $2
`

type UpdateProfileParams struct {
	ID          string        `json:"id"`
	MerchantID  string        `json:"merchant_id"`
	DisplayName string        `json:"display_name"`
	SimSlot     sql.NullInt32 `json:"sim_slot"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.ID,
		arg.MerchantID,
		arg.DisplayName,
		arg.SimSlot,
	)
	return err
}

const updateProfileStatus = `-- name: UpdateProfileStatus :exec
UPDATE public.payment_profiles
SET status = $3
WHERE id = $1 AND merchant_id = $2
`

type UpdateProfileStatusParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
	Status     string `json:"status"`
}

func (q *Queries) UpdateProfileStatus(ctx context.Context, arg UpdateProfileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileStatus, arg.ID, arg.MerchantID, arg.Status)
	return err
}

const updateTrackedBalance = `-- name: UpdateTrackedBalance :exec
UPDATE public.payment_profiles
SET tracked_balance        = $2,
    balance_last_synced_at = now()
WHERE id = $1
`

type UpdateTrackedBalanceParams struct {
	ID             string        `json:"id"`
	TrackedBalance sql.NullInt64 `json:"tracked_balance"`
}

func (q *Queries) UpdateTrackedBalance(ctx context.Context, arg UpdateTrackedBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateTrackedBalance, arg.ID, arg.TrackedBalance)
	return err
}
