// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countSessionsCurrentPeriod = `-- name: CountSessionsCurrentPeriod :one
SELECT session_count_current_period FROM public.merchants WHERE id = $1
`

func (q *Queries) CountSessionsCurrentPeriod(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsCurrentPeriod, id)
	var session_count_current_period int64
	err := row.Scan(&session_count_current_period)
	return session_count_current_period, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO public.checkout_sessions (
    id, merchant_id, payment_profile_id, source, amount, currency,
    customer, metadata, return_url, cancel_url, payment_link_id, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, merchant_id, payment_profile_id, source, amount, currency, customer, metadata, sender_number_claim, trx_id_claim, claim_submitted_at, confirmed_at, status, needs_review, review_reason, expires_at, return_url, cancel_url, payment_link_id, created_at, updated_at
`

type CreateSessionParams struct {
	ID               string          `json:"id"`
	MerchantID       string          `json:"merchant_id"`
	PaymentProfileID string          `json:"payment_profile_id"`
	Source           string          `json:"source"`
	Amount           int64           `json:"amount"`
	Currency         string          `json:"currency"`
	Customer         json.RawMessage `json:"customer"`
	Metadata         json.RawMessage `json:"metadata"`
	ReturnUrl        string          `json:"return_url"`
	CancelUrl        string          `json:"cancel_url"`
	PaymentLinkID    sql.NullString  `json:"payment_link_id"`
	ExpiresAt        time.Time       `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.MerchantID,
		arg.PaymentProfileID,
		arg.Source,
		arg.Amount,
		arg.Currency,
		arg.Customer,
		arg.Metadata,
		arg.ReturnUrl,
		arg.CancelUrl,
		arg.PaymentLinkID,
		arg.ExpiresAt,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentProfileID,
		&i.Source,
		&i.Amount,
		&i.Currency,
		&i.Customer,
		&i.Metadata,
		&i.SenderNumberClaim,
		&i.TrxIDClaim,
		&i.ClaimSubmittedAt,
		&i.ConfirmedAt,
		&i.Status,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.ExpiresAt,
		&i.ReturnUrl,
		&i.CancelUrl,
		&i.PaymentLinkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findExpiredMatchCandidates = `-- name: FindExpiredMatchCandidates :many
SELECT cs.id, cs.merchant_id, cs.payment_profile_id, cs.source, cs.amount, cs.currency, cs.customer, cs.metadata, cs.sender_number_claim, cs.trx_id_claim, cs.claim_submitted_at, cs.confirmed_at, cs.status, cs.needs_review, cs.review_reason, cs.expires_at, cs.return_url, cs.cancel_url, cs.payment_link_id, cs.created_at, cs.updated_at
FROM public.checkout_sessions cs
WHERE cs.merchant_id         = $1
  AND cs.payment_profile_id  = $2
  AND cs.amount              BETWEEN $3 AND $4
  AND cs.sender_number_claim = $5
  AND cs.status              = 'pending'
  AND cs.expires_at          < now()
  AND cs.expires_at          > now() - interval '24 hours'
ORDER BY cs.created_at ASC
`

type FindExpiredMatchCandidatesParams struct {
	MerchantID        string         `json:"merchant_id"`
	PaymentProfileID  string         `json:"payment_profile_id"`
	Amount            int64          `json:"amount"`
	Amount_2          int64          `json:"amount_2"`
	SenderNumberClaim sql.NullString `json:"sender_number_claim"`
}

func (q *Queries) FindExpiredMatchCandidates(ctx context.Context, arg FindExpiredMatchCandidatesParams) ([]CheckoutSession, error) {
	rows, err := q.db.QueryContext(ctx, findExpiredMatchCandidates,
		arg.MerchantID,
		arg.PaymentProfileID,
		arg.Amount,
		arg.Amount_2,
		arg.SenderNumberClaim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckoutSession{}
	for rows.Next() {
		var i CheckoutSession
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.PaymentProfileID,
			&i.Source,
			&i.Amount,
			&i.Currency,
			&i.Customer,
			&i.Metadata,
			&i.SenderNumberClaim,
			&i.TrxIDClaim,
			&i.ClaimSubmittedAt,
			&i.ConfirmedAt,
			&i.Status,
			&i.NeedsReview,
			&i.ReviewReason,
			&i.ExpiresAt,
			&i.ReturnUrl,
			&i.CancelUrl,
			&i.PaymentLinkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMatchCandidates = `-- name: FindMatchCandidates :many
SELECT cs.id, cs.merchant_id, cs.payment_profile_id, cs.source, cs.amount, cs.currency, cs.customer, cs.metadata, cs.sender_number_claim, cs.trx_id_claim, cs.claim_submitted_at, cs.confirmed_at, cs.status, cs.needs_review, cs.review_reason, cs.expires_at, cs.return_url, cs.cancel_url, cs.payment_link_id, cs.created_at, cs.updated_at
FROM public.checkout_sessions cs
WHERE cs.merchant_id          = $1
  AND cs.payment_profile_id   = $2
  AND cs.amount               BETWEEN $3 AND $4
  AND cs.sender_number_claim  = $5
  AND cs.status               = 'pending'
ORDER BY cs.created_at ASC
`

type FindMatchCandidatesParams struct {
	MerchantID        string         `json:"merchant_id"`
	PaymentProfileID  string         `json:"payment_profile_id"`
	Amount            int64          `json:"amount"`
	Amount_2          int64          `json:"amount_2"`
	SenderNumberClaim sql.NullString `json:"sender_number_claim"`
}

func (q *Queries) FindMatchCandidates(ctx context.Context, arg FindMatchCandidatesParams) ([]CheckoutSession, error) {
	rows, err := q.db.QueryContext(ctx, findMatchCandidates,
		arg.MerchantID,
		arg.PaymentProfileID,
		arg.Amount,
		arg.Amount_2,
		arg.SenderNumberClaim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckoutSession{}
	for rows.Next() {
		var i CheckoutSession
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.PaymentProfileID,
			&i.Source,
			&i.Amount,
			&i.Currency,
			&i.Customer,
			&i.Metadata,
			&i.SenderNumberClaim,
			&i.TrxIDClaim,
			&i.ClaimSubmittedAt,
			&i.ConfirmedAt,
			&i.Status,
			&i.NeedsReview,
			&i.ReviewReason,
			&i.ExpiresAt,
			&i.ReturnUrl,
			&i.CancelUrl,
			&i.PaymentLinkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, merchant_id, payment_profile_id, source, amount, currency, customer, metadata, sender_number_claim, trx_id_claim, claim_submitted_at, confirmed_at, status, needs_review, review_reason, expires_at, return_url, cancel_url, payment_link_id, created_at, updated_at FROM public.checkout_sessions
WHERE id = $1 AND merchant_id = $2
LIMIT 1
`

type GetSessionParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID, arg.MerchantID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentProfileID,
		&i.Source,
		&i.Amount,
		&i.Currency,
		&i.Customer,
		&i.Metadata,
		&i.SenderNumberClaim,
		&i.TrxIDClaim,
		&i.ClaimSubmittedAt,
		&i.ConfirmedAt,
		&i.Status,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.ExpiresAt,
		&i.ReturnUrl,
		&i.CancelUrl,
		&i.PaymentLinkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionForPublicCheckout = `-- name: GetSessionForPublicCheckout :one
SELECT
    cs.id, cs.merchant_id, cs.payment_profile_id, cs.amount, cs.currency,
    cs.status, cs.needs_review, cs.review_reason, cs.expires_at, cs.created_at,
    cs.sender_number_claim, cs.trx_id_claim, cs.confirmed_at,
    m.name  AS merchant_name,
    m.logo_url AS merchant_logo_url,
    m.brand_color AS merchant_brand_color,
    m.support_email AS merchant_support_email,
    m.support_phone AS merchant_support_phone
FROM public.checkout_sessions cs
JOIN public.merchants m ON m.id = cs.merchant_id
WHERE cs.id = $1
LIMIT 1
`

type GetSessionForPublicCheckoutRow struct {
	ID                   string         `json:"id"`
	MerchantID           string         `json:"merchant_id"`
	PaymentProfileID     string         `json:"payment_profile_id"`
	Amount               int64          `json:"amount"`
	Currency             string         `json:"currency"`
	Status               string         `json:"status"`
	NeedsReview          bool           `json:"needs_review"`
	ReviewReason         sql.NullString `json:"review_reason"`
	ExpiresAt            time.Time      `json:"expires_at"`
	CreatedAt            time.Time      `json:"created_at"`
	SenderNumberClaim    sql.NullString `json:"sender_number_claim"`
	TrxIDClaim           sql.NullString `json:"trx_id_claim"`
	ConfirmedAt          sql.NullTime   `json:"confirmed_at"`
	MerchantName         string         `json:"merchant_name"`
	MerchantLogoUrl      string         `json:"merchant_logo_url"`
	MerchantBrandColor   string         `json:"merchant_brand_color"`
	MerchantSupportEmail string         `json:"merchant_support_email"`
	MerchantSupportPhone string         `json:"merchant_support_phone"`
}

func (q *Queries) GetSessionForPublicCheckout(ctx context.Context, id string) (GetSessionForPublicCheckoutRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionForPublicCheckout, id)
	var i GetSessionForPublicCheckoutRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PaymentProfileID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SenderNumberClaim,
		&i.TrxIDClaim,
		&i.ConfirmedAt,
		&i.MerchantName,
		&i.MerchantLogoUrl,
		&i.MerchantBrandColor,
		&i.MerchantSupportEmail,
		&i.MerchantSupportPhone,
	)
	return i, err
}

const incrMerchantSessionCount = `-- name: IncrMerchantSessionCount :exec
UPDATE public.merchants
SET session_count_current_period = session_count_current_period + 1
WHERE id = $1
`

func (q *Queries) IncrMerchantSessionCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrMerchantSessionCount, id)
	return err
}

const listSessions = `-- name: ListSessions :many
SELECT id, merchant_id, payment_profile_id, source, amount, currency, customer, metadata, sender_number_claim, trx_id_claim, claim_submitted_at, confirmed_at, status, needs_review, review_reason, expires_at, return_url, cancel_url, payment_link_id, created_at, updated_at FROM public.checkout_sessions
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSessionsParams struct {
	MerchantID string `json:"merchant_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]CheckoutSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckoutSession{}
	for rows.Next() {
		var i CheckoutSession
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.PaymentProfileID,
			&i.Source,
			&i.Amount,
			&i.Currency,
			&i.Customer,
			&i.Metadata,
			&i.SenderNumberClaim,
			&i.TrxIDClaim,
			&i.ClaimSubmittedAt,
			&i.ConfirmedAt,
			&i.Status,
			&i.NeedsReview,
			&i.ReviewReason,
			&i.ExpiresAt,
			&i.ReturnUrl,
			&i.CancelUrl,
			&i.PaymentLinkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSessionCount = `-- name: ResetSessionCount :exec
UPDATE public.merchants SET session_count_current_period = 0 WHERE id = $1
`

func (q *Queries) ResetSessionCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, resetSessionCount, id)
	return err
}

const updateSessionClaim = `-- name: UpdateSessionClaim :exec
UPDATE public.checkout_sessions
SET sender_number_claim = $2,
    trx_id_claim        = $3,
    claim_submitted_at  = now(),
    updated_at          = now()
WHERE id = $1
`

type UpdateSessionClaimParams struct {
	ID                string         `json:"id"`
	SenderNumberClaim sql.NullString `json:"sender_number_claim"`
	TrxIDClaim        sql.NullString `json:"trx_id_claim"`
}

func (q *Queries) UpdateSessionClaim(ctx context.Context, arg UpdateSessionClaimParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionClaim, arg.ID, arg.SenderNumberClaim, arg.TrxIDClaim)
	return err
}

const updateSessionConfirmed = `-- name: UpdateSessionConfirmed :exec
UPDATE public.checkout_sessions
SET confirmed_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateSessionConfirmed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSessionConfirmed, id)
	return err
}

const updateSessionNeedsReview = `-- name: UpdateSessionNeedsReview :exec
UPDATE public.checkout_sessions
SET needs_review = $2, review_reason = $3, updated_at = now()
WHERE id = $1
`

type UpdateSessionNeedsReviewParams struct {
	ID           string         `json:"id"`
	NeedsReview  bool           `json:"needs_review"`
	ReviewReason sql.NullString `json:"review_reason"`
}

func (q *Queries) UpdateSessionNeedsReview(ctx context.Context, arg UpdateSessionNeedsReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionNeedsReview, arg.ID, arg.NeedsReview, arg.ReviewReason)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE public.checkout_sessions
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateSessionStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.ID, arg.Status)
	return err
}
