// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sms_messages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const findDuplicateTrxID = `-- name: FindDuplicateTrxID :one
SELECT id FROM public.sms_messages
WHERE provider     = $1
  AND parse_status = 'parsed'
  AND parsed->>'trx_id' = $2
LIMIT 1
`

type FindDuplicateTrxIDParams struct {
	Provider string                `json:"provider"`
	Parsed   pqtype.NullRawMessage `json:"parsed"`
}

func (q *Queries) FindDuplicateTrxID(ctx context.Context, arg FindDuplicateTrxIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findDuplicateTrxID, arg.Provider, arg.Parsed)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getHeldSMSForProfile = `-- name: GetHeldSMSForProfile :many
SELECT id, merchant_id, device_id, payment_profile_id, provider, account_type, raw_text, parsed, parse_status, match_status, matched_session_id, source, sim_slot, received_at, created_at FROM public.sms_messages
WHERE payment_profile_id = $1
  AND match_status       = 'held'
  AND parsed->>'sender_number' = $2
  AND (parsed->>'amount')::bigint = $3
ORDER BY received_at ASC
`

type GetHeldSMSForProfileParams struct {
	PaymentProfileID sql.NullString        `json:"payment_profile_id"`
	Parsed           pqtype.NullRawMessage `json:"parsed"`
	Parsed_2         pqtype.NullRawMessage `json:"parsed_2"`
}

func (q *Queries) GetHeldSMSForProfile(ctx context.Context, arg GetHeldSMSForProfileParams) ([]SmsMessage, error) {
	rows, err := q.db.QueryContext(ctx, getHeldSMSForProfile, arg.PaymentProfileID, arg.Parsed, arg.Parsed_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsMessage{}
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.DeviceID,
			&i.PaymentProfileID,
			&i.Provider,
			&i.AccountType,
			&i.RawText,
			&i.Parsed,
			&i.ParseStatus,
			&i.MatchStatus,
			&i.MatchedSessionID,
			&i.Source,
			&i.SimSlot,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSMSMessage = `-- name: GetSMSMessage :one
SELECT id, merchant_id, device_id, payment_profile_id, provider, account_type, raw_text, parsed, parse_status, match_status, matched_session_id, source, sim_slot, received_at, created_at FROM public.sms_messages WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSMSMessage(ctx context.Context, id string) (SmsMessage, error) {
	row := q.db.QueryRowContext(ctx, getSMSMessage, id)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.DeviceID,
		&i.PaymentProfileID,
		&i.Provider,
		&i.AccountType,
		&i.RawText,
		&i.Parsed,
		&i.ParseStatus,
		&i.MatchStatus,
		&i.MatchedSessionID,
		&i.Source,
		&i.SimSlot,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertSMSMessage = `-- name: InsertSMSMessage :one
INSERT INTO public.sms_messages (
    id, merchant_id, device_id, payment_profile_id, provider, account_type,
    raw_text, parse_status, match_status, source, sim_slot, received_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, merchant_id, device_id, payment_profile_id, provider, account_type, raw_text, parsed, parse_status, match_status, matched_session_id, source, sim_slot, received_at, created_at
`

type InsertSMSMessageParams struct {
	ID               string         `json:"id"`
	MerchantID       string         `json:"merchant_id"`
	DeviceID         sql.NullString `json:"device_id"`
	PaymentProfileID sql.NullString `json:"payment_profile_id"`
	Provider         string         `json:"provider"`
	AccountType      string         `json:"account_type"`
	RawText          string         `json:"raw_text"`
	ParseStatus      string         `json:"parse_status"`
	MatchStatus      string         `json:"match_status"`
	Source           string         `json:"source"`
	SimSlot          sql.NullInt32  `json:"sim_slot"`
	ReceivedAt       time.Time      `json:"received_at"`
}

func (q *Queries) InsertSMSMessage(ctx context.Context, arg InsertSMSMessageParams) (SmsMessage, error) {
	row := q.db.QueryRowContext(ctx, insertSMSMessage,
		arg.ID,
		arg.MerchantID,
		arg.DeviceID,
		arg.PaymentProfileID,
		arg.Provider,
		arg.AccountType,
		arg.RawText,
		arg.ParseStatus,
		arg.MatchStatus,
		arg.Source,
		arg.SimSlot,
		arg.ReceivedAt,
	)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.DeviceID,
		&i.PaymentProfileID,
		&i.Provider,
		&i.AccountType,
		&i.RawText,
		&i.Parsed,
		&i.ParseStatus,
		&i.MatchStatus,
		&i.MatchedSessionID,
		&i.Source,
		&i.SimSlot,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSMSStatsByProvider = `-- name: ListSMSStatsByProvider :many
SELECT
    provider,
    parse_status,
    DATE(created_at AT TIME ZONE 'Asia/Dhaka') AS day,
    COUNT(*)::bigint AS cnt
FROM public.sms_messages
WHERE created_at > now() - interval '30 days'
GROUP BY provider, parse_status, day
ORDER BY day DESC, provider
`

type ListSMSStatsByProviderRow struct {
	Provider    string    `json:"provider"`
	ParseStatus string    `json:"parse_status"`
	Day         time.Time `json:"day"`
	Cnt         int64     `json:"cnt"`
}

func (q *Queries) ListSMSStatsByProvider(ctx context.Context) ([]ListSMSStatsByProviderRow, error) {
	rows, err := q.db.QueryContext(ctx, listSMSStatsByProvider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSMSStatsByProviderRow{}
	for rows.Next() {
		var i ListSMSStatsByProviderRow
		if err := rows.Scan(
			&i.Provider,
			&i.ParseStatus,
			&i.Day,
			&i.Cnt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedSMS = `-- name: ListUnmatchedSMS :many
SELECT id, merchant_id, device_id, payment_profile_id, provider, account_type, raw_text, parsed, parse_status, match_status, matched_session_id, source, sim_slot, received_at, created_at FROM public.sms_messages
WHERE merchant_id  = $1
  AND match_status IN ('unmatched', 'held', 'suspect', 'failed')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnmatchedSMSParams struct {
	MerchantID string `json:"merchant_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListUnmatchedSMS(ctx context.Context, arg ListUnmatchedSMSParams) ([]SmsMessage, error) {
	rows, err := q.db.QueryContext(ctx, listUnmatchedSMS, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsMessage{}
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.DeviceID,
			&i.PaymentProfileID,
			&i.Provider,
			&i.AccountType,
			&i.RawText,
			&i.Parsed,
			&i.ParseStatus,
			&i.MatchStatus,
			&i.MatchedSessionID,
			&i.Source,
			&i.SimSlot,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSMSMatchStatus = `-- name: UpdateSMSMatchStatus :exec
UPDATE public.sms_messages
SET match_status       = $2,
    matched_session_id = $3
WHERE id = $1
`

type UpdateSMSMatchStatusParams struct {
	ID               string         `json:"id"`
	MatchStatus      string         `json:"match_status"`
	MatchedSessionID sql.NullString `json:"matched_session_id"`
}

func (q *Queries) UpdateSMSMatchStatus(ctx context.Context, arg UpdateSMSMatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSMSMatchStatus, arg.ID, arg.MatchStatus, arg.MatchedSessionID)
	return err
}

const updateSMSParsed = `-- name: UpdateSMSParsed :exec
UPDATE public.sms_messages
SET parsed       = $2,
    parse_status = 'parsed',
    provider     = $3,
    account_type = $4
WHERE id = $1
`

type UpdateSMSParsedParams struct {
	ID          string                `json:"id"`
	Parsed      pqtype.NullRawMessage `json:"parsed"`
	Provider    string                `json:"provider"`
	AccountType string                `json:"account_type"`
}

func (q *Queries) UpdateSMSParsed(ctx context.Context, arg UpdateSMSParsedParams) error {
	_, err := q.db.ExecContext(ctx, updateSMSParsed,
		arg.ID,
		arg.Parsed,
		arg.Provider,
		arg.AccountType,
	)
	return err
}
