// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_members.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*) FROM public.team_members WHERE merchant_id = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, merchantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamMembers, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT tm.merchant_id, tm.user_id, tm.role, tm.invited_by, tm.created_at, u.email, u.full_name
FROM public.team_members tm
JOIN public.users u ON u.id = tm.user_id
WHERE tm.merchant_id = $1 AND tm.user_id = $2
LIMIT 1
`

type GetTeamMemberParams struct {
	MerchantID string `json:"merchant_id"`
	UserID     string `json:"user_id"`
}

type GetTeamMemberRow struct {
	MerchantID string         `json:"merchant_id"`
	UserID     string         `json:"user_id"`
	Role       string         `json:"role"`
	InvitedBy  sql.NullString `json:"invited_by"`
	CreatedAt  time.Time      `json:"created_at"`
	Email      string         `json:"email"`
	FullName   string         `json:"full_name"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (GetTeamMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getTeamMember, arg.MerchantID, arg.UserID)
	var i GetTeamMemberRow
	err := row.Scan(
		&i.MerchantID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.Email,
		&i.FullName,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, avatar_url, is_platform_admin, locale, created_at FROM public.users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsPlatformAdmin,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}

const inviteTeamMember = `-- name: InviteTeamMember :exec
INSERT INTO public.team_members (merchant_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (merchant_id, user_id) DO NOTHING
`

type InviteTeamMemberParams struct {
	MerchantID string         `json:"merchant_id"`
	UserID     string         `json:"user_id"`
	Role       string         `json:"role"`
	InvitedBy  sql.NullString `json:"invited_by"`
}

func (q *Queries) InviteTeamMember(ctx context.Context, arg InviteTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, inviteTeamMember,
		arg.MerchantID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.merchant_id, tm.user_id, tm.role, tm.invited_by, tm.created_at, u.email, u.full_name
FROM public.team_members tm
JOIN public.users u ON u.id = tm.user_id
WHERE tm.merchant_id = $1
ORDER BY tm.created_at ASC
`

type ListTeamMembersRow struct {
	MerchantID string         `json:"merchant_id"`
	UserID     string         `json:"user_id"`
	Role       string         `json:"role"`
	InvitedBy  sql.NullString `json:"invited_by"`
	CreatedAt  time.Time      `json:"created_at"`
	Email      string         `json:"email"`
	FullName   string         `json:"full_name"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, merchantID string) ([]ListTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM public.team_members
WHERE merchant_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	MerchantID string `json:"merchant_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.MerchantID, arg.UserID)
	return err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :exec
UPDATE public.team_members
SET role = $3
WHERE merchant_id = $1 AND user_id = $2
`

type UpdateTeamMemberRoleParams struct {
	MerchantID string `json:"merchant_id"`
	UserID     string `json:"user_id"`
	Role       string `json:"role"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamMemberRole, arg.MerchantID, arg.UserID, arg.Role)
	return err
}
