// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countWebhookEndpoints = `-- name: CountWebhookEndpoints :one
SELECT COUNT(*) FROM public.webhook_endpoints
WHERE merchant_id = $1 AND status = 'active'
`

func (q *Queries) CountWebhookEndpoints(ctx context.Context, merchantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebhookEndpoints, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO public.webhook_deliveries (
    id, endpoint_id, merchant_id, event_type, payload
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, endpoint_id, merchant_id, event_type, payload, attempt_count, next_retry_at, status, last_response_code, created_at, delivered_at
`

type CreateWebhookDeliveryParams struct {
	ID         string          `json:"id"`
	EndpointID string          `json:"endpoint_id"`
	MerchantID string          `json:"merchant_id"`
	EventType  string          `json:"event_type"`
	Payload    json.RawMessage `json:"payload"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, createWebhookDelivery,
		arg.ID,
		arg.EndpointID,
		arg.MerchantID,
		arg.EventType,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.MerchantID,
		&i.EventType,
		&i.Payload,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.Status,
		&i.LastResponseCode,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO public.webhook_endpoints (
    id, merchant_id, url, secret, events
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, merchant_id, url, secret, events, status, created_at
`

type CreateWebhookEndpointParams struct {
	ID         string          `json:"id"`
	MerchantID string          `json:"merchant_id"`
	Url        string          `json:"url"`
	Secret     string          `json:"secret"`
	Events     json.RawMessage `json:"events"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, createWebhookEndpoint,
		arg.ID,
		arg.MerchantID,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
UPDATE public.webhook_endpoints
SET status = 'disabled'
WHERE id = $1 AND merchant_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookEndpoint, arg.ID, arg.MerchantID)
	return err
}

const getPendingDeliveries = `-- name: GetPendingDeliveries :many
SELECT wd.id, wd.endpoint_id, wd.merchant_id, wd.event_type, wd.payload, wd.attempt_count, wd.next_retry_at, wd.status, wd.last_response_code, wd.created_at, wd.delivered_at, we.url, we.secret, we.status AS endpoint_status
FROM public.webhook_deliveries wd
JOIN public.webhook_endpoints we ON we.id = wd.endpoint_id
WHERE wd.status       = 'pending'
  AND wd.next_retry_at <= now()
  AND we.status        = 'active'
ORDER BY wd.next_retry_at ASC
LIMIT $1
`

type GetPendingDeliveriesRow struct {
	ID               string          `json:"id"`
	EndpointID       string          `json:"endpoint_id"`
	MerchantID       string          `json:"merchant_id"`
	EventType        string          `json:"event_type"`
	Payload          json.RawMessage `json:"payload"`
	AttemptCount     int32           `json:"attempt_count"`
	NextRetryAt      time.Time       `json:"next_retry_at"`
	Status           string          `json:"status"`
	LastResponseCode sql.NullInt32   `json:"last_response_code"`
	CreatedAt        time.Time       `json:"created_at"`
	DeliveredAt      sql.NullTime    `json:"delivered_at"`
	Url              string          `json:"url"`
	Secret           string          `json:"secret"`
	EndpointStatus   string          `json:"endpoint_status"`
}

func (q *Queries) GetPendingDeliveries(ctx context.Context, limit int32) ([]GetPendingDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingDeliveriesRow{}
	for rows.Next() {
		var i GetPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.MerchantID,
			&i.EventType,
			&i.Payload,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.Status,
			&i.LastResponseCode,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.Url,
			&i.Secret,
			&i.EndpointStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, merchant_id, url, secret, events, status, created_at FROM public.webhook_endpoints
WHERE id = $1 AND merchant_id = $2
LIMIT 1
`

type GetWebhookEndpointParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpoint, arg.ID, arg.MerchantID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliveriesForEndpoint = `-- name: ListDeliveriesForEndpoint :many
SELECT id, endpoint_id, merchant_id, event_type, payload, attempt_count, next_retry_at, status, last_response_code, created_at, delivered_at FROM public.webhook_deliveries
WHERE endpoint_id = $1 AND merchant_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDeliveriesForEndpointParams struct {
	EndpointID string `json:"endpoint_id"`
	MerchantID string `json:"merchant_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListDeliveriesForEndpoint(ctx context.Context, arg ListDeliveriesForEndpointParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveriesForEndpoint,
		arg.EndpointID,
		arg.MerchantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.MerchantID,
			&i.EventType,
			&i.Payload,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.Status,
			&i.LastResponseCode,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, merchant_id, url, secret, events, status, created_at FROM public.webhook_endpoints
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context, merchantID string) ([]WebhookEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookEndpoints, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDelivery = `-- name: ResetDelivery :exec
UPDATE public.webhook_deliveries
SET attempt_count = 0,
    status        = 'pending',
    next_retry_at = now()
WHERE id = $1 AND merchant_id = $2
`

type ResetDeliveryParams struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) ResetDelivery(ctx context.Context, arg ResetDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, resetDelivery, arg.ID, arg.MerchantID)
	return err
}

const updateDeliveryFailed = `-- name: UpdateDeliveryFailed :exec
UPDATE public.webhook_deliveries
SET attempt_count      = attempt_count + 1,
    next_retry_at      = $2,
    status             = $3,
    last_response_code = $4
WHERE id = $1
`

type UpdateDeliveryFailedParams struct {
	ID               string        `json:"id"`
	NextRetryAt      time.Time     `json:"next_retry_at"`
	Status           string        `json:"status"`
	LastResponseCode sql.NullInt32 `json:"last_response_code"`
}

func (q *Queries) UpdateDeliveryFailed(ctx context.Context, arg UpdateDeliveryFailedParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryFailed,
		arg.ID,
		arg.NextRetryAt,
		arg.Status,
		arg.LastResponseCode,
	)
	return err
}

const updateDeliverySuccess = `-- name: UpdateDeliverySuccess :exec
UPDATE public.webhook_deliveries
SET status       = 'delivered',
    delivered_at = now(),
    last_response_code = $2
WHERE id = $1
`

type UpdateDeliverySuccessParams struct {
	ID               string        `json:"id"`
	LastResponseCode sql.NullInt32 `json:"last_response_code"`
}

func (q *Queries) UpdateDeliverySuccess(ctx context.Context, arg UpdateDeliverySuccessParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliverySuccess, arg.ID, arg.LastResponseCode)
	return err
}
