version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - nolintlint
    - exhaustive
    - gofmt
    - goimports
    - misspell

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  goimports:
    local-prefixes: github.com/Seizmann/RexiO-Pay

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
