package devices

import (
	"database/sql"
	"errors"
	"net/http"
	"strings"

	"github.com/Seizmann/RexiO-Pay/backend/internal/api/merchant/common"
	"github.com/Seizmann/RexiO-Pay/backend/internal/apierr"
	devicecrypto "github.com/Seizmann/RexiO-Pay/backend/internal/crypto"
	dbpkg "github.com/Seizmann/RexiO-Pay/backend/internal/db"
	db "github.com/Seizmann/RexiO-Pay/backend/internal/db/sqlc"
	"github.com/go-chi/chi/v5"
)

// PairHandler handles the unauthenticated device pairing exchange. The pairing
// token is the one generated by the merchant dashboard and expires server-side.
type PairHandler struct {
	queries       *db.Queries
	encryptionKey []byte
}

func NewPairHandler(pool *dbpkg.Pool, encryptionKey []byte) *PairHandler {
	return &PairHandler{queries: db.New(pool.SqlDB), encryptionKey: encryptionKey}
}
func (h *PairHandler) Routes() chi.Router { r := chi.NewRouter(); r.Post("/", h.Pair); return r }

type pairRequest struct {
	PairingToken string `json:"pairing_token"`
	DeviceSecret string `json:"device_secret"`
}

func (h *PairHandler) Pair(w http.ResponseWriter, r *http.Request) {
	var req pairRequest
	if !common.DecodeJSON(w, r, &req) {
		return
	}
	req.PairingToken = strings.TrimSpace(req.PairingToken)
	req.DeviceSecret = strings.TrimSpace(req.DeviceSecret)
	if req.PairingToken == "" || len(req.DeviceSecret) < 16 {
		apierr.Render(w, http.StatusBadRequest, apierr.CodeInvalidRequest, "pairing_token and a device_secret are required")
		return
	}
	item, err := h.queries.GetDeviceByPairingToken(r.Context(), sql.NullString{String: req.PairingToken, Valid: true})
	if errors.Is(err, sql.ErrNoRows) {
		apierr.Render(w, http.StatusUnauthorized, apierr.CodeUnauthorized, "invalid or expired pairing token")
		return
	}
	if err != nil {
		apierr.Internal(w, err)
		return
	}
	ciphertext, nonce, err := devicecrypto.Encrypt(h.encryptionKey, []byte(req.DeviceSecret))
	if err != nil {
		apierr.Internal(w, err)
		return
	}
	if err := h.queries.StorePairedDevice(r.Context(), db.StorePairedDeviceParams{ID: item.ID, SecretCiphertext: ciphertext, SecretNonce: nonce}); err != nil {
		apierr.Internal(w, err)
		return
	}
	common.WriteJSON(w, http.StatusOK, map[string]any{"device_id": item.ID, "merchant_id": item.MerchantID, "status": "active"})
}
