package pay.rexio.engine.data.local

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One received SMS awaiting upload. The autogenerated row id doubles as the
 * opaque client_id echoed back by POST /v1/device/sms acks, which is how acked
 * rows are located for deletion.
 */
@Entity(tableName = "outbox")
data class OutboxEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val sender: String,
    @ColumnInfo(name = "raw_body") val rawBody: String,
    /** 0-based SIM slot as reported by the firmware; null when undetected. */
    @ColumnInfo(name = "sim_slot") val simSlot: Int?,
    /** Epoch millis of reception. */
    @ColumnInfo(name = "received_at") val receivedAt: Long,
    /** Provider key (bkash/nagad) derived from config sender_ids when known. */
    val provider: String?,
    val synced: Boolean = false,
    /** Fetch count; diagnostics for the dashboard. */
    val attempts: Int = 0,
    /** Epoch millis until which this row is skipped after exhausting retries. */
    @ColumnInfo(name = "cooldown_until") val cooldownUntil: Long = 0,
)
